"""
Config defines the cities and connections between them for the standard Pandemic Game.
"""
CITIES = [
    ["San Francisco", "blue"],
    ["Chicago", "blue"],
    ["Atlanta", "blue"],
    ["Montreal", "blue"],
    ["New York", "blue"],
    ["Washington", "blue"],
    ["London", "blue"],
    ["Madrid", "blue"],
    ["Paris", "blue"],
    ["Essen", "blue"],
    ["Milan", "blue"],
    ["St. Petersburg", "blue"],
    ["Los Angeles", "yellow"],
    ["Mexico City", "yellow"],
    ["Miami", "yellow"],
    ["Bogota", "yellow"],
    ["Lima", "yellow"],
    ["Santiago", "yellow"],
    ["Buenos Aires", "yellow"],
    ["Sao Paulo", "yellow"],
    ["Lagos", "yellow"],
    ["Johannesburg", "yellow"],
    ["Khartoum", "yellow"],
    ["Kinshasa", "yellow"],
    ["Algiers", "black"],
    ["Istanbul", "black"],
    ["Cairo", "black"],
    ["Moscow", "black"],
    ["Baghdad", "black"],
    ["Tehran", "black"],
    ["Riyadh", "black"],
    ["Karachi", "black"],
    ["Delhi", "black"],
    ["Mumbai", "black"],
    ["Chennai", "black"],
    ["Kolkata", "black"],
    ["Beijing", "red"],
    ["Seoul", "red"],
    ["Tokyo", "red"],
    ["Shanghai", "red"],
    ["Osaka", "red"],
    ["Taipei", "red"],
    ["Hong Kong", "red"],
    ["Bangkok", "red"],
    ["Jakarta", "red"],
    ["Ho Chi Minh City", "red"],
    ["Manila", "red"],
    ["Sydney", "red"],
]

CITY_CONNECTIONS = [
    ["San Francisco", ["Chicago", "Los Angeles", "Tokyo", "Manila"]],
    ["Chicago", ["San Francisco", "Los Angeles", "Mexico City", "Atlanta", "Montreal"]],
    ["Atlanta", ["Chicago", "Washington", "Miami"]],
    ["Montreal", ["Chicago", "New York", "Washington"]],
    ["Washington", ["Atlanta", "Montreal", "New York", "Miami"]],
    ["New York", ["Montreal", "Washington", "Madrid", "London"]],
    ["London", ["New York", "Madrid", "Paris", "Essen"]],
    ["Madrid", ["New York", "London", "Paris", "Sao Paulo", "Algiers"]],
    ["Paris", ["London", "Madrid", "Essen", "Milan", "Algiers"]],
    ["Essen", ["London", "Paris", "Milan", "St. Petersburg"]],
    ["Milan", ["Paris", "Essen", "Istanbul"]],
    ["St. Petersburg", ["Essen", "Istanbul", "Moscow"]],
    ["Los Angeles", ["San Francisco", "Chicago", "Mexico City", "Sydney"]],
    ["Mexico City", ["Los Angeles", "Chicago", "Miami", "Lima", "Bogota"]],
    ["Miami", ["Atlanta", "Washington", "Mexico City", "Bogota"]],
    ["Bogota", ["Mexico City", "Miami", "Lima", "Buenos Aires", "Sao Paulo"]],
    ["Lima", ["Mexico City", "Santiago"]],
    ["Santiago", ["Lima"]],
    ["Buenos Aires", ["Bogota", "Sao Paulo"]],
    ["Sao Paulo", ["Madrid", "Bogota", "Buenos Aires", "Lagos"]],
    ["Lagos", ["Sao Paulo", "Kinshasa", "Khartoum"]],
    ["Kinshasa", ["Lagos", "Khartoum", "Johannesburg"]],
    ["Johannesburg", ["Kinshasa", "Khartoum"]],
    ["Khartoum", ["Kinshasa", "Johannesburg", "Cairo"]],
    ["Algiers", ["Madrid", "Paris", "Istanbul", "Cairo"]],
    ["Cairo", ["Khartoum", "Algiers", "Istanbul", "Baghdad", "Riyadh"]],
    ["Istanbul", ["Milan", "St. Petersburg", "Algiers", "Cairo", "Moscow", "Baghdad"]],
    ["Moscow", ["St. Petersburg", "Istanbul", "Tehran"]],
    ["Baghdad", ["Cairo", "Istanbul", "Tehran", "Riyadh", "Karachi"]],
    ["Tehran", ["Moscow", "Baghdad", "Karachi", "Delhi"]],
    ["Riyadh", ["Cairo", "Baghdad", "Karachi"]],
    ["Karachi", ["Baghdad", "Riyadh", "Tehran", "Delhi", "Mumbai"]],
    ["Delhi", ["Tehran", "Karachi", "Mumbai", "Chennai", "Kolkata"]],
    ["Mumbai", ["Karachi", "Delhi", "Chennai"]],
    ["Chennai", ["Mumbai", "Delhi", "Kolkata", "Bangkok", "Jakarta"]],
    ["Kolkata", ["Delhi", "Chennai", "Bangkok", "Hong Kong"]],
    ["Bangkok", ["Chennai", "Kolkata", "Jakarta", "Hong Kong", "Ho Chi Minh City"]],
    ["Jakarta", ["Chennai", "Bangkok", "Ho Chi Minh City", "Sydney"]],
    ["Sydney", ["Los Angeles", "Jakarta", "Manila"]],
    ["Ho Chi Minh City", ["Bangkok", "Jakarta", "Manila", "Hong Kong"]],
    ["Manila", ["San Francisco", "Sydney", "Ho Chi Minh City", "Hong Kong", "Taipei"]],
    ["Hong Kong", ["Kolkata", "Bangkok", "Ho Chi Minh City", "Manila", "Taipei", "Shanghai"]],
    ["Taipei", ["Hong Kong", "Manila", "Shanghai", "Osaka"]],
    ["Shanghai", ["Hong Kong", "Taipei", "Beijing", "Seoul", "Tokyo"]],
    ["Beijing", ["Shanghai", "Seoul"]],
    ["Seoul", ["Beijing", "Shanghai", "Tokyo"]],
    ["Tokyo", ["San Francisco", "Shanghai", "Seoul", "Osaka"]],
    ["Osaka", ["Taipei", "Tokyo"]],
]